import re
import json
import base64

def cleanup_mermaid_code(code: str) -> str:
    """
    Standardized cleanup for Mermaid diagrams generated by LLMs.
    Handles bolding, invalid arrows, missing headers, and unquoted labels.
    """
    if not code:
        return ""
        
    code = code.strip()

    # 1. Handle common bolding issues: **Label** or __Label__
    code = re.sub(r'\*\*(.*?)\*\*', r'\1', code)
    code = re.sub(r'__(.*?)__', r'\1', code)

    # 2. Fix invalid arrows (LLMs sometimes use => or malformed labels)
    code = code.replace("=>", "-->")
    # Fix malformed labels like -->"|label|" to -->|label|
    code = re.sub(r'-->\s*("\|(.*?)\|"|\|(.*?)\|>)', r'-->|\2\3|', code)
    code = re.sub(r'->\s*("\|(.*?)\|"|\|(.*?)\|>)', r'->|\2\3|', code)

    # 3. Ensure a valid header exists
    valid_headers = ['graph', 'flowchart', 'sequenceDiagram', 'classDiagram', 'stateDiagram', 'erDiagram', 'pie', 'gantt', 'gitGraph', 'journey', 'quadrantChart', 'mindmap', 'timeline', 'zenuml', 'architecture']
    if not any(code.startswith(x) for x in valid_headers):
        if "->" in code or "-->" in code:
            code = "graph TD\n" + code

    # 4. Escape/Quote labels that contain special characters but aren't quoted
    def quote_problematic_labels(line):
        patterns = [
            (r'(\[+)(.*?)(\]+)', r'\1"\2"\3'),
            (r'(\(+)(.*?)(\)+)', r'\1"\2"\3'),
            (r'(\{+)(.*?)(\}+)', r'\1"\2"\3'),
            (r'(>)(.*?)([\s\]\)])', r'>"\2"\3')
        ]
        for pattern, replacement in patterns:
            def replacer(match):
                groups = match.groups()
                if len(groups) < 3: return match.group(0)
                prefix, content, suffix = groups
                if content.strip().startswith('"') and content.strip().endswith('"'):
                    return match.group(0)
                if any(c in content for c in ' ()[]{}<>'):
                    return f'{prefix}"{content.strip()}"{suffix}'
                return match.group(0)
            line = re.sub(pattern, replacer, line)
        return line

    # 5. Process lines for labels (only for flowcharts/graphs to avoid breaking sequence diagrams)
    if 'sequenceDiagram' not in code:
        lines = code.split('\n')
        processed_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith('subgraph') or stripped == 'end' or not stripped:
                processed_lines.append(line)
            else:
                processed_lines.append(quote_problematic_labels(line))
        code = '\n'.join(processed_lines)

    # 6. Sequence Diagram specific fixes
    if 'sequenceDiagram' in code:
        # Fix malformed arrows and quoted/colonized targets: DB-->">Auth:" User data -> DB-->>Auth: User data
        code = re.sub(r'([\w\s]+?)\s*(?:--\>|--\>\>|-\>\>|-\>)\s*"(.*?):?"\s*(.*)', r'\1-->>\2: \3', code)
        # Fix cases where colon is misplaced or missing: DB-->>Auth User data -> DB-->>Auth: User data
        code = re.sub(r'(--\>\>|-\>\>|-\>)\s*([\w\s]+)\s+([A-Z/])', r'\1 \2: \3', code)
        # Final cleanup of any double colons or quotes in targets
        code = re.sub(r'->>\s*"(.*?)"', r'->>\1', code)
        code = re.sub(r'-->>\s*"(.*?)"', r'-->>\1', code)
        # Fix sequence diagram notes: Note over A,B -> Note over A, B
        code = re.sub(r'Note\s+(over|left of|right of)\s+([^:]+)', lambda m: f"Note {m.group(1)} {m.group(2).replace(',', ', ')}", code)
        # Fix double spaces from comma replacement
        code = code.replace(',  ', ', ')
            
    return code

def get_mermaid_url(code: str, theme: str = "dark") -> str:
    """
    Generates a mermaid.ink URL for the given code.
    """
    payload = {
        "code": code,
        "mermaid": {"theme": theme, "themeVariables": {"darkMode": True if theme == "dark" else False}}
    }
    json_str = json.dumps(payload)
    # Use standard base64 but replace characters to be URL safe for mermaid.ink
    base64_code = base64.b64encode(json_str.encode('utf-8')).decode('utf-8')
    # Some mermaid.ink versions prefer standard, but let's ensure no / occurs at the end
    base64_code = base64_code.replace('+', '-').replace('/', '_').rstrip('=')
    return f"https://mermaid.ink/img/{base64_code}"
